# Generated by Django 2.2.5 on 2019-09-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20190918_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='best_by',
            field=models.DateField(),
        ),
    ]
