# Generated by Django 2.2.5 on 2019-09-19 11:21

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20190918_2257'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listing',
            managers=[
                ('filtered_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
